import { EmployeeRow } from './types'

export const MOCK_ROWS: EmployeeRow[] = [
  {
    id: '1',
    fullName: 'Amara Osei',
    email: 'amara.osei@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '2',
    fullName: 'Lena Fischer',
    email: 'lena.fischer@acme.com',
    team: 'Product',
    status: 'valid',
    errors: {},
  },
  {
    id: '3',
    fullName: 'James Okafor',
    email: 'james.okafor@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '4',
    fullName: 'Priya Mehta',
    email: 'priya.mehta@acme.com',
    team: 'Design',
    status: 'valid',
    errors: {},
  },
  {
    id: '5',
    fullName: 'Carlos Reyes',
    email: 'carlos.reyes@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '6',
    fullName: 'Sophie Laurent',
    email: 'sophie.laurent@acme.com',
    team: 'Marketing',
    status: 'valid',
    errors: {},
  },
  {
    id: '7',
    fullName: 'Kwame Asante',
    email: 'kwame.asante@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '8',
    fullName: 'Mei Lin',
    email: 'mei.lin@acme.com',
    team: 'Finance',
    status: 'valid',
    errors: {},
  },
  {
    id: '9',
    fullName: 'Tobias Müller',
    email: 'tobias.muller@acme.com',
    team: 'Legal',
    status: 'valid',
    errors: {},
  },
  {
    id: '10',
    fullName: 'Aisha Kamara',
    email: 'aisha.kamara@acme.com',
    team: 'People Ops',
    status: 'valid',
    errors: {},
  },
  {
    id: '11',
    fullName: 'Diego Romero',
    email: 'diego.romero@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '12',
    fullName: 'Hannah Park',
    email: 'hannah.park@acme.com',
    team: 'Product',
    status: 'valid',
    errors: {},
  },
  {
    id: '13',
    fullName: 'Andreas Pedersen',
    email: 'andreas.pedersen@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '14',
    fullName: 'Ethan Brooks',
    email: 'ethan.brooks@acme.com',
    team: 'Design',
    status: 'valid',
    errors: {},
  },
  {
    id: '15',
    fullName: 'Fatima Diallo',
    email: 'fatima.diallo@acme.com',
    team: 'Marketing',
    status: 'valid',
    errors: {},
  },
  {
    id: '16',
    fullName: 'Ravi Sharma',
    email: 'ravi.sharma@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '17',
    fullName: 'Ingrid Svensson',
    email: 'ingrid.svensson@acme.com',
    team: 'Finance',
    status: 'valid',
    errors: {},
  },
  {
    id: '18',
    fullName: 'Omar Faruk',
    email: 'omar.faruk@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '19',
    fullName: 'Yuki Tanaka',
    email: 'yuki.tanaka@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '20',
    fullName: 'Camille Dubois',
    email: 'camille.dubois@acme.com',
    team: 'Legal',
    status: 'valid',
    errors: {},
  },
  {
    id: '21',
    fullName: 'Leo Andersen',
    email: 'leo.andersen@acme.com',
    team: 'Product',
    status: 'valid',
    errors: {},
  },
  {
    id: '22',
    fullName: 'Adaeze Nwosu',
    email: 'adaeze.nwosu@acme.com',
    team: 'People Ops',
    status: 'valid',
    errors: {},
  },
  {
    id: '23',
    fullName: 'Viktor Petrov',
    email: 'viktor.petrov@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '24',
    fullName: 'Isabella Rossi',
    email: 'isabella.rossi@acme.com',
    team: 'Marketing',
    status: 'valid',
    errors: {},
  },
  {
    id: '25',
    fullName: 'Kofi Boateng',
    email: 'kofi.boateng@acme.com',
    team: 'Design',
    status: 'valid',
    errors: {},
  },
  {
    id: '26',
    fullName: 'Layla Mansour',
    email: 'layla.mansour@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '27',
    fullName: 'Finn O\'Brien',
    email: 'finn.obrien@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '28',
    fullName: 'Zara Ahmed',
    email: 'zara.ahmed@acme.com',
    team: 'Finance',
    status: 'valid',
    errors: {},
  },
  {
    id: '29',
    fullName: 'Lucas Fernandez',
    email: 'lucas.fernandez@acme.com',
    team: 'Product',
    status: 'valid',
    errors: {},
  },
  {
    id: '30',
    fullName: 'Nina Johansson',
    email: 'nina.johansson@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '31',
    fullName: 'Samuel Oduya',
    email: 'samuel.oduya@acme.com',
    team: 'Legal',
    status: 'valid',
    errors: {},
  },
  {
    id: '32',
    fullName: 'Hana Nakamura',
    email: 'hana.nakamura@acme.com',
    team: 'Marketing',
    status: 'valid',
    errors: {},
  },
  {
    id: '33',
    fullName: 'Elias Bergström',
    email: 'elias.bergstrom@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '34',
    fullName: 'Chiara Colombo',
    email: 'chiara.colombo@acme.com',
    team: 'Design',
    status: 'valid',
    errors: {},
  },
  {
    id: '35',
    fullName: 'Arjun Nair',
    email: 'arjun.nair@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '36',
    fullName: 'Malia Fonoti',
    email: 'malia.fonoti@acme.com',
    team: 'People Ops',
    status: 'valid',
    errors: {},
  },
  {
    id: '37',
    fullName: 'Ben Kirsch',
    email: 'ben.kirsch@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '38',
    fullName: 'Emre Demir',
    email: 'emre.demir@acme.com',
    team: 'Finance',
    status: 'valid',
    errors: {},
  },
  {
    id: '39',
    fullName: 'Sasha Volkov',
    email: 'sasha.volkov@acme.com',
    team: 'Product',
    status: 'valid',
    errors: {},
  },
  {
    id: '40',
    fullName: 'Grace Wanjiku',
    email: 'grace.wanjiku@acme.com',
    team: 'Marketing',
    status: 'valid',
    errors: {},
  },
  {
    id: '41',
    fullName: 'Mateo García',
    email: 'mateo.garcia@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '42',
    fullName: 'Nadia Popescu',
    email: 'nadia.popescu@acme.com',
    team: 'Legal',
    status: 'valid',
    errors: {},
  },
  {
    id: '43',
    fullName: 'Taiwo Adeyemi',
    email: 'taiwo.adeyemi@acme.com',
    team: 'Sales',
    status: 'valid',
    errors: {},
  },
  {
    id: '44',
    fullName: 'Julia Novak',
    email: 'julia.novak@acme.com',
    team: 'Design',
    status: 'valid',
    errors: {},
  },
  {
    id: '45',
    fullName: 'Ahmad Khalil',
    email: 'ahmad.khalil@acme.com',
    team: 'Engineering',
    status: 'valid',
    errors: {},
  },
  {
    id: '46',
    fullName: 'Sara Lindqvist',
    email: 'sara.lindqvist@acme.com',
    team: 'People Ops',
    status: 'valid',
    errors: {},
  },
  {
    id: '47',
    fullName: 'Pierre Martin',
    email: 'pierre.martin@acme.com',
    team: 'Finance',
    status: 'valid',
    errors: {},
  },
  // --- Error rows ---
  {
    id: '48',
    fullName: 'Marcus Webb',
    email: 'marcus.webb@acme',
    team: 'Engineering',
    status: 'error',
    errors: {
      email: 'Email address is missing a valid domain (e.g. ".com")',
    },
  },
  {
    id: '49',
    fullName: 'Olivia Chen',
    email: '',
    team: 'Product',
    status: 'error',
    errors: {
      email: 'Email address is required',
    },
  },
  {
    id: '50',
    fullName: '',
    email: 'unknown.entry@acme.com',
    team: 'Marketing',
    status: 'error',
    errors: {
      fullName: 'Full name is required',
    },
  },
  // --- Duplicate rows ---
  {
    id: '51',
    fullName: 'Priya Mehta',
    email: 'priya.mehta@acme.com',
    team: 'Design',
    status: 'duplicate',
    errors: {
      email: 'This email is already used in row 4 - possible duplicate entry',
    },
    duplicateOf: '4',
  },
  {
    id: '52',
    fullName: 'Kwame Asante',
    email: 'kwame.asante@acme.com',
    team: 'Engineering',
    status: 'duplicate',
    errors: {
      email: 'This email is already used in row 7 - possible duplicate entry',
    },
    duplicateOf: '7',
  },
]
